# ArgoCD Installation Guide
# This file contains commands to install ArgoCD

# Create ArgoCD namespace
# kubectl create namespace argocd

# Install ArgoCD
# kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

# Expose ArgoCD Server (LoadBalancer)
# kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'

# Or expose via NodePort
# kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "NodePort"}}'

# Get initial admin password
# kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d

# Port forward to access ArgoCD UI (alternative)
# kubectl port-forward svc/argocd-server -n argocd 8080:443

# Login to ArgoCD CLI
# argocd login <ARGOCD_SERVER>

# Change admin password
# argocd account update-password

---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argocd
spec:
  type: NodePort
  ports:
  - port: 443
    targetPort: 8080
    nodePort: 30443
    protocol: TCP
    name: https
  selector:
    app.kubernetes.io/name: argocd-server
